# This sets up an Elasticsearch cluster with 3 nodes.
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es
spec:
  version: 7.15.2
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: true
    podTemplate:
      metadata:
        labels:
          app: es
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 0.75
            limits:
              memory: 2Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
    count: 3
  http:
    service:
      spec:
        # expose this cluster Service with a LoadBalancer
        type: LoadBalancer
---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
    name: es
    annotations:
      replicas-max: "1"
spec:
    version: 7.15.2
    count: 1
    elasticsearchRef:
        name: es
    secureSettings:
    - secretName: kibana-saved-objects-encrypted-key
    http:
        service:
            spec:
                type: LoadBalancer
                ports:
                - name: https
                  protocol: TCP
                  port: 443
                  targetPort: 5601
    podTemplate:
        metadata:
            labels:
                app: es
        spec:
            containers:
            - name: kibana
              resources:
                requests:
                  memory: 1Gi
                  cpu: 0.6
                limits:
                  memory: 1Gi
                  cpu: 0.75
